---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporary-namespaces-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporary-namespaces
rules:
- apiGroups:
  - ""
  resources: 
  - namespaces
  verbs:
  - list
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: temporary-namespaces
subjects:
- kind: ServiceAccount
  name: temporary-namespaces-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: temporary-namespaces
  apiGroup: rbac.authorization.k8s.io
